import pyautogui as pg
import time

time.sleep(3)
pg.hotkey("ctrl","alt","t")
time.sleep(3)
pg.typewrite("cd Desktop")
pg.hotkey("Enter")
time.sleep(1)
pg.typewrite("vim music.txt")
pg.hotkey("Enter")
time.sleep(1)
pg.hotkey("e")
pg.hotkey("Enter")  
time.sleep(3)
pg.hotkey("Ctrl","win","r")
time.sleep(3)
pg.hotkey("ctrl","alt","t")
time.sleep(3)
pg.typewrite("cd Videos")
time.sleep(3)
pg.hotkey("Enter")
time.sleep(3)
pg.typewrite("xdg-open")
time.sleep(1)
pg.hotkey("Space")
pg.typewrite("He")
time.sleep(1)
pg.hotkey("Tab")
time.sleep(1)
pg.hotkey("Enter")
time.sleep(4)
pg.hotkey("Ctrl","win","l")
time.sleep(3)
pg.hotkey("alt","shift","tab")
time.sleep(2)
pg.typewrite("exit")
pg.hotkey("Enter")
time.sleep(2)
pg.hotkey("alt","shift","tab")
time.sleep(2)
pg.press("Up",43)
pg.hotkey("Home")
pg.hotkey("v")
pg.hotkey("Down")#0
time.sleep(8)
pg.hotkey("Down")#1
time.sleep(4)
pg.hotkey("Down")#2
time.sleep(4)
pg.hotkey("Down")#3
time.sleep(4)
pg.hotkey("Down")#4
time.sleep(4)
pg.hotkey("Down")#5
time.sleep(4)
pg.hotkey("Down")#6
time.sleep(3)
pg.hotkey("Down")#7
time.sleep(4)
pg.hotkey("Down")#8
time.sleep(4)
pg.hotkey("Down")#9
time.sleep(4)
pg.hotkey("Down")#10
time.sleep(4)
pg.hotkey("Down")#11
time.sleep(4)
pg.hotkey("Down")#12
time.sleep(4)
pg.hotkey("Down")#13
time.sleep(4)
pg.hotkey("Down")#14
time.sleep(20)
pg.hotkey("Down")#15
time.sleep(2)
pg.hotkey("Down")#16
time.sleep(2)
pg.hotkey("Down")#17
time.sleep(4)
pg.hotkey("Down")#18
time.sleep(4)
pg.hotkey("Down")#19
time.sleep(4)
pg.hotkey("Down")#20
time.sleep(4)
pg.hotkey("Down")#21
time.sleep(3)
pg.hotkey("Down")#22
time.sleep(4)
pg.hotkey("Down")#23
time.sleep(22)
pg.hotkey("Down")#24
time.sleep(4)
pg.hotkey("Down")#25
time.sleep(4)
pg.hotkey("Down")#26
time.sleep(4)
pg.hotkey("Down")#27
time.sleep(4)
pg.hotkey("Down")#28
time.sleep(4)
pg.hotkey("Down")#29
time.sleep(4)
pg.hotkey("Down")#30
time.sleep(3)
pg.hotkey("Down")#31
time.sleep(5)
pg.hotkey("Down")#32
time.sleep(7)
pg.hotkey("Down")#33
time.sleep(4)
pg.hotkey("Down")#34
time.sleep(4)
pg.hotkey("Down")#35
time.sleep(4)
pg.hotkey("Down")#36
time.sleep(4)
pg.hotkey("Down")#37
time.sleep(8)
pg.hotkey("Down")#38
time.sleep(8)
pg.hotkey("Down")#39
time.sleep(3)
pg.hotkey("Down")#40
time.sleep(5)
pg.hotkey("Down")#41
time.sleep(8)
pg.hotkey("Down")#42
pg.hotkey("End")#42